services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ny_taxi
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./ny_taxi:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - same-network-as-airflow

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - same-network-as-airflow

volumes:
  pgadmin_data:

networks:
  same-network-as-airflow:
    external:
      name: week_2_default